---
- name: Aplicar configuracion de OSPF
  cisco.ios.ios_config:
    src: "{{ playbook_dir }}/../configs/{{ inventory_hostname }}/{{ inventory_hostname }}_rt_ospf.cfg"
  register: apply_ospf_result
  notify: Guardar configuracion