---
- name: Aplicar configuracion de EIGRP
  cisco.ios.ios_config:
    src: "{{ playbook_dir }}/../configs/{{ inventory_hostname }}/{{ inventory_hostname }}_rt_eigrp.cfg"
  register: apply_eigrp_result
  notify: Guardar configuracion