---
- name: Defincion de variables locales
  ansible.builtin.set_fact:
    services: "{{ modelo.infra_spec.devices[inventory_hostname].services }}"

- name: Renderizar template Jinja2 para configurarcion de SERVICES
  ansible.builtin.template:
    src: "{{ playbook_dir }}/roles/services/templates/services_{{ item.type }}.j2"
    dest: "{{ playbook_dir }}/{{ item.dest }}/{{ inventory_hostname }}/{{ item.orden }}{{ inventory_hostname }}_services.{{ item.ext }}"
    mode: "0644"
  register: services_result
  loop:
    - {type: cfg, dest: "../configs", ext: cfg, orden: ""}
    - {type: doc, dest: "../doc/modulos", ext: md, orden: "1.1"}

- name: Mostrar resultado de la generacion de configuracion de SERVICES
  ansible.builtin.debug:
    var: services_result