---
- name: Check if a file exists
  ansible.builtin.stat:
    path: '{{ playbook_dir }}/../configs/{{ inventory_hostname }}/{{ inventory_hostname }}_rt_vrf.cfg'
  register: file_check

- name: Aplicar configuracion de VRF
  cisco.ios.ios_config:
    src: "{{ playbook_dir }}/../configs/{{ inventory_hostname }}/{{ inventory_hostname }}_rt_vrf.cfg"
  register: apply_vrf_result
  notify: Guardar configuracion
  when: file_check.stat.exists