---
- name: Aplicar configuracion de MPLS
  cisco.ios.ios_config:
    src: "{{ playbook_dir }}/../configs/{{ inventory_hostname }}/{{ inventory_hostname }}_rt_mpls.cfg"
  register: apply_mpls_result
  notify: Guardar configuracion