---
- name: Aplicar configuracion de interfaces MGMT
  cisco.ios.ios_config:
    src: "{{ playbook_dir }}/../configs/{{ inventory_hostname }}/{{ inventory_hostname }}_int_mgmt.cfg"
  register: apply_mgmt_result
  notify: Guardar configuracion