---
- name: Aplicar configuracion de interfaces SVI
  cisco.ios.ios_config:
    src: "{{ playbook_dir }}/../configs/{{ inventory_hostname }}/{{ inventory_hostname }}_int_svi.cfg"
  register: apply_svi_result
  notify: Guardar configuracion