---
- name: Defincion de variables locales
  ansible.builtin.set_fact:
    vlans: "{{ modelo.infra_spec.devices[inventory_hostname].vlans }}"

- name: Renderizar template Jinja2 para configurarcion de VLANs
  ansible.builtin.template:
    src: "{{ playbook_dir }}/roles/vlans/templates/vlans_{{ item.type }}.j2"
    dest: "{{ playbook_dir }}/{{ item.dest }}/{{ inventory_hostname }}/{{ item.orden }}{{ inventory_hostname }}_vlans.{{ item.ext }}"
    mode: "0644"
  when: vlans is defined and vlans|length > 0
  register: vlans_result
  loop:
    - {type: cfg, dest: "../configs", ext: cfg, orden: ""}
    - {type: doc, dest: "../doc/modulos", ext: md, orden: "1.1"}

- name: Mostrar resultado de la generacion de configuracion de VLANs
  ansible.builtin.debug:
    var: vlans_result
  when: vlans is defined and vlans|length > 0