# Playbook para generar codigo utilizando templates Jinja2
---
- name: Generar codigo desde templates Jinja2 para configuracion de ROUTERS BB
  hosts: "{{ modelo.hosts_groups.rt_all }}, {{ modelo.hosts_groups.sw_core }}"
  gather_facts: false

  vars_files:
    - ../modelo_datos/modelo.yml

  tasks:
    - name: Defincion de variables locales
      ansible.builtin.set_fact:
        routers_bb: "{{ modelo.infra_spec.devices[inventory_hostname].routers_bb }}"

    - name: Renderizar template Jinja2 para configurarcion de ROUTERS BB
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/routers_bb_{{ item.type }}.j2"
        dest: "{{ playbook_dir }}/{{ item.dest }}/{{ item.orden }}{{ inventory_hostname }}_routers_bb.{{ item.ext }}"
        mode: "0644"
      register: routers_bb_result
      loop:
        - {type: cfg, dest: "../configs", ext: cfg, orden: ""}
        - {type: doc, dest: "../doc/modulos", ext: md, orden: "1.1"}
  
    - name: Mostrar resultado de la generacion de configuracion de ROUTERS BB
      ansible.builtin.debug:
        var: routers_bb_result

- name: Generar codigo desde templates Jinja2 para interfaces P-PE
  hosts: "{{ modelo.hosts_groups.rt_all }}, {{ modelo.hosts_groups.sw_core }}"
  gather_facts: false

  vars_files:
    - ../modelo_datos/modelo.yml

  tasks:
    - name: Defincion de variables locales
      ansible.builtin.set_fact:
        interfaces: "{{ modelo.infra_spec.devices[inventory_hostname].interfaces }}"

    - name: Renderizar template Jinja2 para configurarcion de interfaces P-PE
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/int_rt_{{ item.type }}.j2"
        dest: "{{ playbook_dir }}/{{ item.dest }}/{{ item.orden }}{{ inventory_hostname }}_int_rt.{{ item.ext }}"
        mode: "0644"
      register: int_rt_result
      loop:
        - {type: cfg, dest: "../configs", ext: cfg, orden: ""}
        - {type: doc, dest: "../doc/modulos", ext: md, orden: "1.1"}

    - name: Mostrar resultado de la generacion de configuracion de interfaces de P-PE
      ansible.builtin.debug:
        var: int_rt_result

- name: Generar codigo desde templates Jinja2 para interfaces ACCESS
  hosts: "{{ modelo.hosts_groups.sw_all }}"
  gather_facts: false

  vars_files:
    - ../modelo_datos/modelo.yml

  tasks:
    - name: Defincion de variables locales
      ansible.builtin.set_fact:
        interfaces: "{{ modelo.infra_spec.devices[inventory_hostname].interfaces }}"

    - name: Renderizar template Jinja2 para configurarcion de interfaces ACCESS
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/int_access_{{ item.type }}.j2"
        dest: "{{ playbook_dir }}/{{ item.dest }}/{{ item.orden }}{{ inventory_hostname }}_int_access.{{ item.ext }}"
        mode: "0644"
      register: int_access_result
      loop:
        - {type: cfg, dest: "../configs", ext: cfg, orden: ""}
        - {type: doc, dest: "../doc/modulos", ext: md, orden: "1.1"}

    - name: Mostrar resultado de la generacion de configuracion de interfaces de ACCESS
      ansible.builtin.debug:
        var: int_access_result

- name: Generar codigo desde templates Jinja2 para interfaces TRUNK
  hosts: "{{ modelo.hosts_groups.sw_all }}"
  gather_facts: false

  vars_files:
    - ../modelo_datos/modelo.yml

  tasks:
    - name: Defincion de variables locales
      ansible.builtin.set_fact:
        interfaces: "{{ modelo.infra_spec.devices[inventory_hostname].interfaces }}"

    - name: Renderizar template Jinja2 para configurarcion de interfaces TRUNK
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/int_trunk_{{ item.type }}.j2"
        dest: "{{ playbook_dir }}/{{ item.dest }}/{{ item.orden }}{{ inventory_hostname }}_int_trunk.{{ item.ext }}"
        mode: "0644"
      register: int_trunk_result
      loop:
        - {type: cfg, dest: "../configs", ext: cfg, orden: ""}
        - {type: doc, dest: "../doc/modulos", ext: md, orden: "1.1"}

    - name: Mostrar resultado de la generacion de configuracion de interfaces TRUNK
      ansible.builtin.debug:
        var: int_trunk_result

- name: Generar codigo desde templates Jinja2 para interfaces L2 y L3 MGMT
  hosts: "{{ modelo.hosts_groups.sw_all }}"
  gather_facts: false

  vars_files:
    - ../modelo_datos/modelo.yml

  tasks:
    - name: Defincion de variables locales
      ansible.builtin.set_fact:
        interfaces: "{{ modelo.infra_spec.devices[inventory_hostname].interfaces }}"

    - name: Renderizar template Jinja2 para configurarcion de interfaces L2 y L3 MGMT
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/int_mgmt_{{ item.type }}.j2"
        dest: "{{ playbook_dir }}/{{ item.dest }}/{{ item.orden }}{{ inventory_hostname }}_int_mgmt.{{ item.ext }}"
        mode: "0644"
      register: int_mgmt_result
      loop:
        - {type: cfg, dest: "../configs", ext: cfg, orden: ""}
        - {type: doc, dest: "../doc/modulos", ext: md, orden: "1.1"}

    - name: Mostrar resultado de la generacion de configuracion de interfaces L2 y L3 MGMT
      ansible.builtin.debug:
        var: int_mgmt_result

- name: Generar codigo desde templates Jinja2 para configuracion de VLANs
  hosts: "{{ modelo.hosts_groups.sw_all }}"
  gather_facts: false

  vars_files:
    - ../modelo_datos/modelo.yml

  tasks:
    - name: Defincion de variables locales
      ansible.builtin.set_fact:
        vlans: "{{ modelo.infra_spec.devices[inventory_hostname].vlans }}"

    - name: Renderizar template Jinja2 para configurarcion de VLANs
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/vlans_{{ item.type }}.j2"
        dest: "{{ playbook_dir }}/{{ item.dest }}/{{ item.orden }}{{ inventory_hostname }}_vlans.{{ item.ext }}"
        mode: "0644"
      register: vlans_result
      loop:
        - {type: cfg, dest: "../configs", ext: cfg, orden: ""}
        - {type: doc, dest: "../doc/modulos", ext: md, orden: "1.1"}

    - name: Mostrar resultado de la generacion de configuracion de VLANs
      ansible.builtin.debug:
        var: vlans_result

- name: Generar codigo desde templates Jinja2 para configuracion de SVI y VRRP
  hosts: "{{ modelo.hosts_groups.sw_core }}, {{ modelo.hosts_groups.sw_it }}"
  gather_facts: false

  vars_files:
    - ../modelo_datos/modelo.yml

  tasks:
    - name: Defincion de variables locales
      ansible.builtin.set_fact:
        interfaces: "{{ modelo.infra_spec.devices[inventory_hostname].interfaces }}"

    - name: Renderizar template Jinja2 para configurarcion de SVI y VRRP
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/int_svi_{{ item.type }}.j2"
        dest: "{{ playbook_dir }}/{{ item.dest }}/{{ item.orden }}{{ inventory_hostname }}_int_svi.{{ item.ext }}"
        mode: "0644"
      register: svi_vrrp_result
      loop:
        - {type: cfg, dest: "../configs", ext: cfg, orden: ""}
        - {type: doc, dest: "../doc/modulos", ext: md, orden: "1.1"}
      
    - name: Mostrar resultado de la generacion de configuracion de SVI y VRRP
      ansible.builtin.debug:
        var: svi_vrrp_result
  
- name: Generar codigo desde templates Jinja2 para configuracion de ROUTERS
  hosts: "{{ modelo.hosts_groups.sw_core }}, {{ modelo.hosts_groups.sw_it }}"
  gather_facts: false

  vars_files:
    - ../modelo_datos/modelo.yml

  tasks:
    - name: Defincion de variables locales
      ansible.builtin.set_fact:
        routers: "{{ modelo.infra_spec.devices[inventory_hostname].routers }}"

    - name: Renderizar template Jinja2 para configurarcion de ROUTERS
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/routers_{{ item.type }}.j2"
        dest: "{{ playbook_dir }}/{{ item.dest }}/{{ item.orden }}{{ inventory_hostname }}_routers.{{ item.ext }}"
        mode: "0644"
      register: routers_result
      loop:
        - {type: cfg, dest: "../configs", ext: cfg, orden: ""}
        - {type: doc, dest: "../doc/modulos", ext: md, orden: "1.1"}
  
    - name: Mostrar resultado de la generacion de configuracion de ROUTERS
      ansible.builtin.debug:
        var: routers_result

- name: Generar codigo desde templates Jinja2 para configuracion de SERVICES
  hosts: "{{ modelo.hosts_groups.sw_all }}"
  gather_facts: false

  vars_files:
    - ../modelo_datos/modelo.yml

  tasks:
    - name: Defincion de variables locales
      ansible.builtin.set_fact:
        services: "{{ modelo.infra_spec.devices[inventory_hostname].services }}"

    - name: Renderizar template Jinja2 para configurarcion de SERVICES
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/services_{{ item.type }}.j2"
        dest: "{{ playbook_dir }}/{{ item.dest }}/{{ item.orden }}{{ inventory_hostname }}_services.{{ item.ext }}"
        mode: "0644"
      register: services_result
      loop:
        - {type: cfg, dest: "../configs", ext: cfg, orden: ""}
        - {type: doc, dest: "../doc/modulos", ext: md, orden: "1.1"}
    
    - name: Mostrar resultado de la generacion de configuracion de SERVICES
      ansible.builtin.debug:
        var: services_result